available_compounds = {
    2018: {
        1: ['ULTRASOFT', 'SUPERSOFT', 'SOFT'],
        2: ['SUPERSOFT', 'SOFT', 'MEDIUM'],
        3: ['ULTRASOFT', 'SOFT', 'MEDIUM'],
        4: ['ULTRASOFT', 'SUPERSOFT', 'SOFT'],
        5: ['SUPERSOFT', 'SOFT', 'MEDIUM'],
        6: ['HYPERSOFT', 'ULTRASOFT', 'SUPERSOFT'],
        7: ['HYPERSOFT', 'ULTRASOFT', 'SUPERSOFT'],
        8: ['ULTRASOFT', 'SUPERSOFT', 'SOFT'],
        9: ['ULTRASOFT', 'SUPERSOFT', 'SOFT'],
        10: ['SOFT', 'MEDIUM', 'HARD'],
        11: ['ULTRASOFT', 'SOFT', 'MEDIUM'],
        12: ['ULTRASOFT', 'SOFT', 'MEDIUM'],
        13: ['SUPERSOFT', 'SOFT', 'MEDIUM'],
        14: ['SUPERSOFT', 'SOFT', 'MEDIUM'],
        15: ['HYPERSOFT', 'ULTRASOFT', 'SOFT'],
        16: ['HYPERSOFT', 'ULTRASOFT', 'SUPERSOFT'],
        17: ['SUPERSOFT', 'SOFT', 'MEDIUM'],
        18: ['ULTRASOFT', 'SUPERSOFT', 'SOFT'],
        19: ['HYPERSOFT', 'ULTRASOFT', 'SUPERSOFT'],
        20: ['SUPERSOFT', 'SOFT', 'MEDIUM'],
        21: ['HYPERSOFT', 'ULTRASOFT', 'SUPERSOFT']
    },
    
    2019: {
        1: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        2: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        3: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        4: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        5: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        6: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        7: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        8: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        9: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        10: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        11: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        12: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        13: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        14: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        15: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        16: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        17: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        18: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},   
        19: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        20: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        21: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    },
    2020: {
        1: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        2: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        3: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        4: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        5: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        6: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        7: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        8: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        9: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        10: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        11: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        12: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        13: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        14: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        15: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        16: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        17: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    },
    2021: {
        1: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        2: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        3: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        4: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        5: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        6: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        7: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        8: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        9: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        10: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        11: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        12: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        13: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        14: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        15: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        16: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        17: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},   
        18: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        19: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        20: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        21: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        22: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    },
    2022: {
        1: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        2: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        3: {'SOFT': 'C5', 'MEDIUM': 'C3', 'HARD': 'C2'},
        4: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        5: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        6: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        7: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        8: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        9: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        10: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        11: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        12: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        13: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        14: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        15: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        16: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        17: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        18: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        19: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        20: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        21: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        22: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    },
    2023: {
        1: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        2: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        3: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        4: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        5: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        6: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        7: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        8: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        9: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        10: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        11: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        12: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        13: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        14: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        15: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        16: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        17: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        18: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        19: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        20: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        21: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        22: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    },
    2024: {
        1: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        2: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        3: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        4: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        5: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        6: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        7: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        8: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        9: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        10: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        11: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        12: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        13: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        14: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        15: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        16: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        17: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        18: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        19: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        20: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        21: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        22: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        23: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        24: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    },
    2025: {
        1: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        2: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        3: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        4: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        5: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        6: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        7: {'SOFT': 'C6', 'MEDIUM': 'C5', 'HARD': 'C4'},
        8: {'SOFT': 'C6', 'MEDIUM': 'C5', 'HARD': 'C4'},
        9: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        10: {'SOFT': 'C6', 'MEDIUM': 'C5', 'HARD': 'C4'},
        11: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        12: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        13: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C1'},
        14: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        15: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        16: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        17: {'SOFT': 'C6', 'MEDIUM': 'C5', 'HARD': 'C4'},
        18: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        19: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C1'},
        20: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C2'},
        21: {'SOFT': 'C4', 'MEDIUM': 'C3', 'HARD': 'C2'},
        22: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'},
        23: {'SOFT': 'C3', 'MEDIUM': 'C2', 'HARD': 'C1'},
        24: {'SOFT': 'C5', 'MEDIUM': 'C4', 'HARD': 'C3'}
    }
}

def get_available_compounds(year, round_number):
    """Returns the available compounds for a given year and round number."""
    if year == 2018:
        return available_compounds[2018].get(round_number, [])
    elif year in available_compounds and round_number in available_compounds[year]:
        return list(available_compounds[year][round_number].values())
    else:
        return []